// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLHOoXTKZbVq_eIcd7BR0BIOUBXg-i3-8',
    appId: '1:733353250714:web:10bcb4efb72f8495adf423',
    messagingSenderId: '733353250714',
    projectId: 'hotcontrol-c90f4',
    authDomain: 'hotcontrol-c90f4.firebaseapp.com',
    storageBucket: 'hotcontrol-c90f4.appspot.com',
    measurementId: 'G-H5ZWMNMKPR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtRLTbZArVGiSkHEcIhS-61fvmI3BjScQ',
    appId: '1:733353250714:android:48c6e456481730b7adf423',
    messagingSenderId: '733353250714',
    projectId: 'hotcontrol-c90f4',
    storageBucket: 'hotcontrol-c90f4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcpeDelhn7QTSJIMtdM-uVgtehzS-1j50',
    appId: '1:733353250714:ios:5aa984d56c3ea9b8adf423',
    messagingSenderId: '733353250714',
    projectId: 'hotcontrol-c90f4',
    storageBucket: 'hotcontrol-c90f4.appspot.com',
    iosBundleId: 'com.example.hotControl',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcpeDelhn7QTSJIMtdM-uVgtehzS-1j50',
    appId: '1:733353250714:ios:5aa984d56c3ea9b8adf423',
    messagingSenderId: '733353250714',
    projectId: 'hotcontrol-c90f4',
    storageBucket: 'hotcontrol-c90f4.appspot.com',
    iosBundleId: 'com.example.hotControl',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBLHOoXTKZbVq_eIcd7BR0BIOUBXg-i3-8',
    appId: '1:733353250714:web:55b23a7871fc212cadf423',
    messagingSenderId: '733353250714',
    projectId: 'hotcontrol-c90f4',
    authDomain: 'hotcontrol-c90f4.firebaseapp.com',
    storageBucket: 'hotcontrol-c90f4.appspot.com',
    measurementId: 'G-D95HZ52VEJ',
  );
}
